### PR TITLE
Alfa test utils

### PR DESCRIPTION
**Pull request by Jym77**
Start of II-7901

### CODE REVIEW

**Comment by Jym77** [comment]
!pr extract

**Comment by Jym77** [comment]
!pr extract

**Comment by Jym77** [comment]
!pr dedupe

**Review by rcj-siteimprove — DISMISSED** [review]
Looks good 💪🏼

**Comment by Jym77** [comment]
!pr extract

**Review by jfer-siteimprove — APPROVED** [review]
LGTM 👍

**Pull request merged**
